server:
  port: ${PORT:8084}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/usuariosdb?sslmode=require
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: WARN
    org.springframework: WARN
    web: WARN
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
