app:
    api:
        version: v1
    version: 0.0.1
logging:
    level:
        com:
            zaxxer:
                hikari: ERROR
        org:
            hibernate: ERROR
            hibernate.SQL: DEBUG
            springframework: ERROR
        root: ERROR
        web: INFO
management:
    endpoints:
        web:
            exposure:
                include: '*'
    server:
        port: 8081
server:
    port: 8080
spring:
    application:
        name: reserva-service
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-test-query: SELECT 1
            connection-timeout: 30000
            idle-timeout: 600000
            keepalive-time: 300000
            max-lifetime: 1800000
            maximum-pool-size: 50
            minimum-idle: 10
            validation-timeout: 5000
        password: a1b2c3d4
        url: jdbc:postgresql://localhost:5432/aulaSmart
        username: dev
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    main:
        allow-circular-references: true
